-- Exercise 1.14
-- Draw the tree illustrating the process generated by the count-change procedure of 1.2.2 in making change for 11 cents. What are the orders of growth of the space and number of steps used by this process as the amount to be changed increases?


countChange amount = cc amount 5  where
    cc amount kindsOfCoins
        | amount == 0       = 1
        | amount < 0 ||
          kindsOfCoins == 0 = 0
        | otherwise         =
            cc amount (kindsOfCoins-1) +
            cc (amount - firstDenomination kindsOfCoins) kindsOfCoins
    firstDenomination kindsOfCoins
        | kindsOfCoins == 1 = 1
        | kindsOfCoins == 2 = 5
        | kindsOfCoins == 3 = 10
        | kindsOfCoins == 4 = 25
        | kindsOfCoins == 5 = 50

main = print $ countChange 11  -- 4


-- Order of growth is Θ(n^5)

-- http://www.billthelizard.com/2009/12/sicp-exercise-114-counting-change.html